/** @type {Record<string, { variant?: number | number[] }>} */
export const targetEntities = {
    'ldns:killer_rabbit': {},
    'ldns:gray_enderman': {},
    'ldns:nonebrain': {},
    'ldns:nullbrain': {},
    'ldns:errormob': {},
    'ldns:strange_chicken': {},
    'ldns:head_only_sheep': {},
    'ldns:dr.naba': {},
    'ldns:onibi': {},
    'ldns:shadow_mob': {},
    'minecraft:zombie': { variant: 1 },
    'minecraft:skeleton': { variant: 1 },
    'minecraft:zombie_pigman': { variant: [1, 2] },
    'ldns:skele_zombie': {},
    'ldns:skeleton_trader': {},
    'ldns:pp': {},
    'ldns:yy': {},
    "ldns:entity787": {},
    "ldns:never_sleep": {},
    "ldns:ov7": {},
    "ldns:ov8": {},
    "ldns:place": {},
    "ldns:possibly": {},
    "ldns:shadow_mob_desert": {},
    "ldns:vill": {},
    "ldns:tbd": {},
    "ldns:binary444": {},
    "ldns:herovoid": {},
    "ldns:public_void": {}
}